###########################
# Travis-CI Configuration #
###########################

# Use a generic environment
language: generic

# Only deploy updates to the master branch
stages:
  - name: deploy
    if: branch = master

# Cache the TeX Live installation
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

################
# Build Stages #
################

# Installation an optimized setup of TeX Live
install: source ./.ci/install.sh

# Build the dissertation
script: make

# Prepare the working area for deployment
before_deploy: source ./.ci/before_deploy.sh

# Deploy the manuscript to gh-pages
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  skip-cleanup: true

